### ISSUE TITLE
hi piyush

### ISSUE THREAD

**Issue by fms12** [piyushraj2340/Plant-Selling-Website#1]
i f your looking this i wann ask you how did you deploy backend and frontend on different server

**Comment by piyushraj2340** [comment]
### Reference for Deploying Backend and Frontend on Different Servers
For a detailed walkthrough on deploying your backend and frontend applications on different servers, please refer to the following video:
[Deploying Backend and Frontend on Different Servers](https://youtu.be/Cfi0mymfKiA?si=lzn64K4zXSmvSVJK)
